cache: yarn

branches:
  only:
    - master

language: node_js
node_js:
  - 7

install:
  - yarn install

script:
  - yarn build

after_success:
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
  - docker build -t $TRAVIS_REPO_SLUG:latest .
  - docker push $TRAVIS_REPO_SLUG
