sudo: required

services:
  - docker

cache: yarn

branches:
  only:
    - master

language: node_js
node_js:
  - 7

install:
  - yarn install

script:
  - yarn build

after_success:
  - sh .travis/deploy-dockerhub.sh
  - echo
  - echo "Heroku deploying..."
  - echo
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy-heroku.sh
